- name: expense backend setup
  hosts: all
  tasks:
    - name: disable default version of nodejs
      ansible.builtin.shell: dnf module disable nodejs -y
    - name: install nodejs
      ansible.builtin.dnf:  module enable nodejs:18 -y 
      name: nodejs
      state: present
    - name: copy backend service
      ansible.builin.file:
      src: backend.service
      dest: /etc/systemd/system/backend.service
    - name: Add application user
      ansible.builtin.user:
      name: expense
    - name: delete old app
      ansible.builtin.file:
      src: /app
      state: absent
    - name:create app directory
      ansible.builtin.file:
      path: /app
      state: directory
    - name: download nodejs
     ansile.builtin.dnf:
     name: nodejs
    - name: download and extract app content
      ansible.builtin.unarchive:
      src: https://expense-artifacts.s3.amazonaws.com/backend.zip 
      dest: /app
      remote_src: yes
     - name: download depensices
      ansible.builti 


    